# DATATON

## Modernisme: Accés Obert Hack the Data!

In [98]:
import pandas as pd

### Step 1. Data Gathering

In [106]:
"""
arquitectura2 = pd.read_csv('dades/arquitectura.csv', header = None, sep = ';', skiprows=[0,1], names=['Nid','Titulo','Tipo','Autor','NumInventario','Altura','Anchura','Coleccion','Inicio','Imagen','SujetoRepresentado','Localizacion','Coleccion','Calle','CodigoCatalogo','Coordenadas','Diocesis','Estado','Genero','MaterialUtilitzat','PartDe','Poblacion','Wikilink'])
cartells2 = pd.read_csv('dades/cartells.csv',  header = None, sep = ';', skiprows=[0,1], names=['Nid','Titulo','Tipo','Autor','NumInventario','Altura','Anchura','Coleccion','Inicio','Imagen','SujetoRepresentado','Localizacion','Coleccion','Calle','CodigoCatalogo','Coordenadas','Diocesis','Estado','Genero','MaterialUtilitzat','PartDe','Poblacion','Wikilink'])
dibuix2 = pd.read_csv('dades/dibuix.csv', header = None, sep = ';', skiprows=[0,1], names=['Nid','Titulo','Tipo','Autor','NumInventario','Altura','Anchura','Coleccion','Inicio','Imagen','SujetoRepresentado','Localizacion','Coleccion','Calle','CodigoCatalogo','Coordenadas','Diocesis','Estado','Genero','MaterialUtilitzat','PartDe','Poblacion','Wikilink'])
escultura2 = pd.read_csv('dades/escultura.csv', header = None, sep = ';', skiprows=[0,1], names=['Nid','Titulo','Tipo','Autor','NumInventario','Altura','Anchura','Coleccion','Inicio','Imagen','SujetoRepresentado','Localizacion','Coleccion','Calle','CodigoCatalogo','Coordenadas','Diocesis','Estado','Genero','MaterialUtilitzat','PartDe','Poblacion','Wikilink'])
estampes2 = pd.read_csv('dades/estampes.csv', header = None, sep = ';', skiprows=[0,1], names=['Nid','Titulo','Tipo','Autor','NumInventario','Altura','Anchura','Coleccion','Inicio','Imagen','SujetoRepresentado','Localizacion','Coleccion','Calle','CodigoCatalogo','Coordenadas','Diocesis','Estado','Genero','MaterialUtilitzat','PartDe','Poblacion','Wikilink'])
medalles2 = pd.read_csv('dades/medalles.csv', header = None, sep = ';', skiprows=[0,1], names=['Nid','Titulo','Tipo','Autor','NumInventario','Altura','Anchura','Coleccion','Inicio','Imagen','SujetoRepresentado','Localizacion','Coleccion','Calle','CodigoCatalogo','Coordenadas','Diocesis','Estado','Genero','MaterialUtilitzat','PartDe','Poblacion','Wikilink'])
moda2 = pd.read_csv('dades/moda.csv', header = None, sep = ';', skiprows=[0,1], names=['Nid','Titulo','Tipo','Autor','NumInventario','Altura','Anchura','Coleccion','Inicio','Imagen','SujetoRepresentado','Localizacion','Coleccion','Calle','CodigoCatalogo','Coordenadas','Diocesis','Estado','Genero','MaterialUtilitzat','PartDe','Poblacion','Wikilink'])
pintura2 = pd.read_csv('dades/pintura.csv', header = None, sep = ';', skiprows=[0,1], names=['Nid','Titulo','Tipo','Autor','NumInventario','Altura','Anchura','Coleccion','Inicio','Imagen','SujetoRepresentado','Localizacion','Coleccion','Calle','CodigoCatalogo','Coordenadas','Diocesis','Estado','Genero','MaterialUtilitzat','PartDe','Poblacion','Wikilink'])
vitrall2 = pd.read_csv('dades/vitrall.csv', header = None, sep = ';', skiprows=[0,1], names=['Nid','Titulo','Tipo','Autor','NumInventario','Altura','Anchura','Coleccion','Inicio','Imagen','SujetoRepresentado','Localizacion','Coleccion','Calle','CodigoCatalogo','Coordenadas','Diocesis','Estado','Genero','MaterialUtilitzat','PartDe','Poblacion','Wikilink'])
"""

arquitectura = pd.read_csv('dades/arquitectura.csv', sep = ';', encoding='latin1')
cartells = pd.read_csv('dades/cartells.csv', sep = ';', encoding='latin1')
dibuix = pd.read_csv('dades/dibuix.csv', sep = ';', encoding='latin1')
estampes = pd.read_csv('dades/estampes.csv', sep = ';', encoding='latin1')
medalles = pd.read_csv('dades/medalles.csv', sep = ';', encoding='latin1')
moda = pd.read_csv('dades/moda.csv', sep = ';', encoding='latin1')
vitrall = pd.read_csv('dades/vitrall.csv', sep = ';', encoding='latin1')

In [107]:
arquitectura.describe()

,Nid,Num. Inventari,Alçada,Amplada,Col·lecció,Subjecte representat,Localització,Col·lecció.1,Codi catàleg,Gènere,Material utilitzat
count,1222.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
mean,642.150573,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,354.436968,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,30.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,335.250000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,641.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,948.750000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,1255.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Step 2. Data cleaning

In [108]:
escultura[0:10]

,Nid,Titulo,Tipo,Autor,NumInventario,Altura,Anchura,Coleccion,Inicio,Imagen,...,Calle,CodigoCatalogo,Coordenadas,Diocesis,Estado,Genero,MaterialUtilitzat,PartDe,Poblacion,Wikilink
0,3615,A Charles Deering,Escultura,Josep Llimona i Bruguera,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Miami,http://www.wikidata.org/entity/Q26835792
1,3616,A Jeroni Estades,Escultura,Josep Llimona i Bruguera,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,S�ller,http://www.wikidata.org/entity/Q26835796
2,3617,A Llu�s Millet i l'Orfe� Catal�,Escultura,Josep Llimona i Bruguera,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,http://www.wikidata.org/entity/Q26835803
3,3618,A Sarah Bernhardt,Escultura,Josep Llimona i Bruguera,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,http://www.wikidata.org/entity/Q26835807
4,3619,A Toribi Duran,Escultura,Josep Llimona i Bruguera,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Barcelona,http://www.wikidata.org/entity/Q26835810
5,3620,A la mem�ria de Antonio L�pez i Luisa Bru,Escultura,Josep Llimona i Bruguera,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,http://www.wikidata.org/entity/Q26835800
6,3621,A una benefectora de la inf�ncia,Escultura,Josep Llimona i Bruguera,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,http://www.wikidata.org/entity/Q26835814
7,3622,A �ngel Guimer�,Escultura,Josep Llimona i Bruguera,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Barcelona,http://www.wikidata.org/entity/Q26835788
8,3623,Adolescent 176,Escultura,Josep Llimona i Bruguera,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cerdanyola del Vall�s,http://www.wikidata.org/entity/Q26835823
9,3624,Adolescent 176a,Escultura,Josep Llimona i Bruguera,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Barcelona,http://www.wikidata.org/entity/Q26835824

In [109]:
arquitectura.describe()

,Nid,Num. Inventari,Alçada,Amplada,Col·lecció,Subjecte representat,Localització,Col·lecció.1,Codi catàleg,Gènere,Material utilitzat
count,1222.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
mean,642.150573,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,354.436968,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,30.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,335.250000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,641.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,948.750000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,1255.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

As escultura df, most ofof the rows are Nan!

In [114]:
#Removing Nans from data
arquitectura_cleaned = arquitectura.dropna(inplace=False)
cartells_cleaned = cartells.dropna(inplace=False)
dibuix_cleaned = dibuix.dropna(inplace=False)
escultura_cleaned = escultura.dropna(inplace=False)
estampes_cleaned = estampes.dropna(inplace=False)
medalles_cleaned = medalles.dropna(inplace=False)
moda_cleaned = moda.dropna(inplace=False)
pintura_cleaned = pintura.dropna(inplace=False)
vitrall_cleaned = vitrall.dropna(inplace=False)

In [117]:
vitrallSubset = vitrall.dropna(inplace=False, subset=['Autor', 'Inici', 'Coordenades'])

In [140]:
vitrallOutput=vitrallSubset[['Autor', 'Inici', 'Coordenades']]
coordinates = vitrallOutput['Coordenades'].str.split(' ')
coordsSplitted = pd.DataFrame({'Lat': coordinates.str[0], 'Lon': coordinates.str[1]})
coordsSplitted

            Lat         Lon
7   2.138978999   41.491266
8   2.138978999   41.491266
9   2.138978999   41.491266
10  2.138978999   41.491266
13  2.170634000  41.3841634
14  2.172725500  41.3814871
19  2.166085100  41.3843172
21  2.178416900  41.3826735
28  2.175479999    41.37915
37  2.648251800  39.5673831
38  1.837696599   41.593305
39  2.166085100  41.3843172
40  2.166085100  41.3843172
55  2.488726400  42.1786177
57  1.108547799  41.1548659
58  1.108547799  41.1548659
62  2,168309700  41.3870489
65  2.639851599  41.9566902
72  2.142239900  41.3754205
74  2.153566999  41.3684399
86  2.183355699  41.3880832
87  1.519380200  41.9941572
88  1.837696599   41.593305
96  2.170705799  41.3952778

In [144]:
vitrallOutput['Latitude'] = coordsSplitted.Lat
vitrallOutput['Longitude'] = coordsSplitted.Lon
vitrallOutput['Coordenades'] = vitrallOutput['Coordenades'].str.replace(' ', ',')
vitrallOutput

/Users/dsolans/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':
/Users/dsolans/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app
/Users/dsolans/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()

,Autor,Inici,Coordenades,Longitude,Latitude
7,Eduard Maria Balcells i Bugas,1900.0,"2.138978999,41.491266",41.491266,2.138978999
8,Eduard Maria Balcells i Bugas,1900.0,"2.138978999,41.491266",41.491266,2.138978999
9,Eduard Maria Balcells i Bugas,1900.0,"2.138978999,41.491266",41.491266,2.138978999
10,annim,1900.0,"2.138978999,41.491266",41.491266,2.138978999
13,Antoni Rigalt i Blanch,1897.0,"2.170634000,41.3841634",41.3841634,2.170634000
14,Antoni Ros i Gell,1902.0,"2.172725500,41.3814871",41.3814871,2.172725500
19,Antoni Rigalt i Blanch,1902.0,"2.166085100,41.3843172",41.3843172,2.166085100
21,Darius Vil s i Fern ndez,1925.0,"2.178416900,41.3826735",41.3826735,2.178416900
28,Jeroni Ferran Granell i Manresa,1907.0,"2.175479999,41.37915",41.37915,2.175479999
37,Darius Vil s i Fern ndez,1916.0,"2.648251800,39.5673831",39.5673831,2.648251800
38,Francesc de Paula Villar i Lozano,1884.0,"1.837696599,41.593305",41.593305,1.837696599
39,Antoni Rigalt i Blanch,1908.0,"2.166085100,41.3843172",41.3843172,2.166085100
40,Enric Sagnier i Villavecchia,1907.0,"2.166085100,41.3843172",41.3843172,2.166085100
55,Rafael Mas¢ i Valent¡,1910.0,"2.488726400,42.1786177",42.1786177,2.488726400
57,Llu¡s Domnech i Montaner,1900.0,"1.108547799,41.1548659",41.1548659,1.108547799
58,Gaspar Homar i Mezquida,1900.0,"1.108547799,41.1548659",41.1548659,1.108547799
62,Bonaventura Bassegoda i Amig¢,1915.0,"2,168309700,41.3870489",41.3870489,"2,168309700"
65,Rafael Mas¢ i Valent¡,1915.0,"2.639851599,41.9566902",41.9566902,2.639851599
72,Francesc Labarta i Planas,1914.0,"2.142239900,41.3754205",41.3754205,2.142239900
74,Joaquim Renart i Garcia,1905.0,"2.153566999,41.3684399",41.3684399,2.153566999
86,Antoni Rigalt i Blanch,1888.0,"2.183355699,41.3880832",41.3880832,2.183355699
87,August Font i Carreras,1910.0,"1.519380200,41.9941572",41.9941572,1.519380200
88,Francesc de Paula Villar i Lozano,1887.0,"1.837696599,41.593305",41.593305,1.837696599
96,Josep Su¤er,1900.0,"2.170705799,41.3952778",41.3952778,2.170705799

In [145]:
vitrallOutput[['Coordenades']].to_csv(path_or_buf="out.csv", encoding='latin1')

In [146]:
vitrallOutput[['Coordenades', 'Inici', 'Autor']].to_csv(path_or_buf="out2.csv", encoding='latin1')